### ISSUE TITLE
The problem with the upload.

### ISSUE THREAD

**Issue by megahamed22** [froala/yii2-froala-editor#10]
Hi thanks for this extension
When I upload address change
Do not be uploaded. and an error message shows
please guide me

> <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
>             'model' => $model,
>             'attribute' => 'content',
>             'options'=>[
>                     'id'=>'content',
>             ],
>             'clientOptions'=>[
>                     'imageManagerLoadURL' => \yii\helpers\Url::to(['/blog-post/load-images']),
>                     'imageUploadURL' => \yii\helpers\Url::to(['/blog-post/upload-image']),
>                     'toolbarInline'=> false,
>                     'theme' =>'royal',
>                     'height' => '400'
>             ]
>     ]); ?>

**Comment by dungphanxuan** [comment]
@megahamed22 Thank you for you report
Please folow that guider for upload image
- View
```php
 <?= \froala\froalaeditor\FroalaEditorWidget::widget([
        'name' => 'body',
        'clientOptions' => [
            'toolbarInline'=> false,
            'height' => 200,
            'theme' =>'royal',//optional: dark, red, gray, royal
            'language'=>'en_gb' ,
            'toolbarButtons' => ['fullscreen', 'bold', 'italic', 'underline', '|', 'paragraphFormat', 'insertImage'],
            'imageUploadParam'=> 'file',
            'imageUploadURL'=> \yii\helpers\Url::to(['/test/upload'])
        ],
        'clientPlugins'=> ['fullscreen', 'paragraph_format', 'image'],
    ]); ?>
```

=> Controller action
```php
public function actionUpload()
    {
        /*Process upload file*/
        //$file = $_FILES['file'];
        Yii::$app->response->format = Response::FORMAT_JSON;

        /*=> Get file link */
        $res = array(
            'link'    => 'Your file url',
        );
        /*Response data*/
        return $res;
    }
```
Document https://www.froala.com/wysiwyg-editor/docs/concepts/image-upload
Tutorial yii2 upload file: http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html

**Comment by stefanneculai** [comment]
@megahamed22 please see: https://github.com/froala/yii2-froala-editor#upload-example
