### ISSUE TITLE
iframeStyleFiles

### ISSUE THREAD

**Issue by cshehadi** [froala/yii2-froala-editor#11]
Hi,

can we add the iframeStyleFiles option to this yii2 widget?  

I don't see it in the list of initClientOptions, so when I set it, it's getting ignored.

Thanks!

-Charlie

**Comment by stefanneculai** [comment]
@cshehadi It is missing. Could you please make a PR?

**Comment by cshehadi** [comment]
Apologies - I've never done a pull request before.  I've submitted one, and will do so in the future if I find a simple change.

**Comment by stefanneculai** [comment]
Thank you.
