### ISSUE TITLE
Problem with custom plugin.

### ISSUE THREAD

**Issue by kevinsmendes** [froala/yii2-froala-editor#19]
Hello there.

I am trying to add a custom plugin, but something seems quite not right. I followed the phpdoc and still couldn't manage to make it work. Here is how I was doing and my solution to the case.

This is my code:
```
# ...
'clientPlugins'   => [
    'align', 'image', 'font_family',
    'font_size', 'image_manager', 'line_breaker',
    'link', 'lists', 'url',
    'video', 'colors', 'paragraph_format',
    'customFieldSelector' => [
        'js' => 'url_for_the_js.js'
    ]
],
# ...
```
This is the error that I receive: 
![image](https://user-images.githubusercontent.com/19570528/28883858-40f72796-7786-11e7-8011-adffc9fb94b1.png) [Image 1]

If I change `public $excludedPlugins;` to `public $excludedPlugins = [];`, the following error occurs:

![image](https://user-images.githubusercontent.com/19570528/28883921-7425afde-7786-11e7-921b-7fdc22ff7c47.png) [Image 2]

If I change `public $excludedPlugins = [];` to `public $excludedPlugins = ['_none'];`, the following error occurs:

![image](https://user-images.githubusercontent.com/19570528/28883969-966388e6-7786-11e7-96a5-530b0ae3dc8a.png) [Image 3]

If I change the line `$pluginsEnabled = array_diff($this->clientPlugins, $this->excludedPlugins ?: []);` to `$pluginsEnabled = array_diff_assoc($this->clientPlugins, $this->excludedPlugins ?: []);`, I go back to error on Image 2.

To make everything work, I had to change the following:

Line 42: `public $excludedPlugins;` to `public $excludedPlugins = [];`
Line 100: `$pluginsEnabled = array_diff($this->clientPlugins, $this->excludedPlugins ?: []);` to `$pluginsEnabled = array_diff_assoc($this->clientPlugins, $this->excludedPlugins ?: []);`
Lines 102 to 106: 
```
if(!empty($pluginsEnabled)){
    foreach($pluginsEnabled as $key =>$item){
        $_pluginsEnabled[$i++] = lcfirst (yii\helpers\Inflector::camelize($item));
    }
}
```
to
```
if(!empty($pluginsEnabled)){
    foreach($pluginsEnabled as $key =>$item){
        $pluginsEnabled[$key] = lcfirst (yii\helpers\Inflector::camelize(is_array($item) ? $key : $item));
    }
    $pluginsEnabled = array_values($pluginsEnabled);
}
```

I am not sure if those changes are right, but it worked for me.

**Comment by kevinsmendes** [comment]
I also edited the FroalaEditorAsset.php to allow the addition to use alias on the js/css file.

I change it from:
```
public function addJs($jsFile)
{
    $this->js[] = $jsFile;
}
```
to:
```
public function addJs($jsFile)
{
    if (strpos($jsFile, '@') !== false)
        $jsFile = \Yii::$app->getAssetManager()->publish(\Yii::getAlias($jsFile))[1];
    $this->js[] = $jsFile;
}
```

**Comment by dungphanxuan** [comment]
Because extension code for standard. So you can extend class for customize what you want,

**Comment by kevinsmendes** [comment]
The PHPDoc of the extension itself tells me I can add custom plugins to it, but the code to run it is wrong. This is why I posted my changes here.

**Comment by nikpok** [comment]
There is no such error raised as described in issue by adding custom plugin code,i can try to fix if this issue can be reproduced.tx.
