### ISSUE TITLE
feature request: select which plugins are loaded

### ISSUE THREAD

**Issue by cshehadi** [froala/yii2-froala-editor#2]
Hi,

I noticed that all plugins are loaded by default. It would be great if we could select which ones to load by passing them as arguments to the yii widget.  Is that a possibility?

-Charlie

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled

**Comment by cshehadi** [comment]
ack, right.  sorry.

On Thu, Mar 10, 2016 at 10:36 AM, Stefan Neculai <notifications@github.com>
wrote:

> https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/yii2-froala-editor/issues/2#issuecomment-194907792>
> .
>



-- 
Make a small loan, Make a big difference - http://www.Kiva.org
