### ISSUE TITLE
Froala no matching package found.

### ISSUE THREAD

**Issue by zhukovsergey** [froala/yii2-froala-editor#22]
When i install:

> composer require --prefer-dist froala/yii2-froala-editor

or

> composer require froala/yii2-froala-editor

i get:

![image](https://user-images.githubusercontent.com/1946769/31057923-135f6226-a715-11e7-8b5f-0c9fcfe0e9f1.png)

But it works with:

>composer require froala/yii2-froala-editor:*

**Comment by dungphanxuan** [comment]
plz try add   "froala/yii2-froala-editor": "^2.6.0" to composer.json file, then run composer update
