### ISSUE TITLE
upload file not exists

### ISSUE THREAD

**Issue by masihfathi** [froala/yii2-froala-editor#23]
i update package to v2.7.0 but in the upload image i got file is empty.

**Comment by masihfathi** [comment]
hi again, the problem still exist, would you plz check this issue.i have that problem with this extension which used froala editor, see this issue(https://github.com/yii2mod/yii2-cms/issues/21). $_FILE is empty.

**Comment by stefanneculai** [comment]
@masihfathi it looks like your server accepts only POST method and that's why it doesn't get the request correctly.

**Comment by masihfathi** [comment]
in the behavior method of the controller it is limited to POST request. in the past version of the frolla editor it works correctly.i change behavior method of the controller to accept all requests but in the upload image action of the controller when i check $file it is empty?!!

**Comment by stefanneculai** [comment]
Are you implementing it as described on: https://github.com/froala/yii2-froala-editor#upload-example? The request method can always be changed by using the editor options: https://www.froala.com/wysiwyg-editor/docs/options#imageUploadMethod.
