### ISSUE TITLE
Trying to get property of non-object for upload file

### ISSUE THREAD

**Issue by MarcoDuizer** [froala/yii2-froala-editor#24]
I try to use the upload function for the extension.
I tried it with the example code and with a working version of a file upload in another controller. With both options i get a 400 error where i see that the file is not uploaded.

in imainge-min-js with formatted layout in chrome it is wrong in line 508: 
`        function G(c, d, e, f) {
            function g() {
                var e = a(this);
                e.off("load"),
                e.addClass("fr-uploading"),
                e.next().is("br") && e.next().remove(),
                b.placeholder.refresh(),
                w(e),
                k(),
                r(),
                b.edit.off(),
                c.onload = function() {
                    B.call(c, e)
                }
                ,
                c.onerror = C,
                c.upload.onprogress = D,
                c.onabort = F,
                e.off("abortUpload").on("abortUpload", function() {
                    4 != c.readyState && c.abort()
                }),
                c.send(d) 
            }`
last line the error is: Failed to load resource: the server responded with a status of 400 (Bad Request)
The controller code works with an upload from another model. And the error is already at the point where the file is being read in the controller:
$model = new UploadForm();`
$model->file = UploadedFile::getInstance($model, 'file');
 $image_name = $model->file->baseName . '.' . $model->file->extension;`
The error in the debug console is: Trying to get property of non-object and the higlighted line is the last line of the code before this ($image_name.......)

Form widget code:
`        
        <?= \froala\froalaeditor\FroalaEditorWidget::widget([
            'model' => $model,
            'attribute' => 'descripcion',
            'clientOptions' => [
                'toolbarInline'=> false,
                'height' => 200,
                'theme' => 'royal',//optional: dark, red, gray, royal
                'language' => 'en_gb' ,
                'toolbarButtons' => ['fullscreen', 'bold', 'italic', 'underline', '|', 'paragraphFormat', 'insertImage'],
                'imageUploadParam' => 'file',
                'imageUploadURL' => \yii\helpers\Url::to(['site/upload/'])
            ],
            'clientPlugins'=> ['fullscreen', 'paragraph_format', 'image'],
        ]); ?>`
`<?php
    namespace backend\models;
    use yii\base\Model;
    use yii\web\UploadedFile;

    /**
     * UploadForm is the model behind the upload form.
     */
    class UploadForm extends Model
    {
        /**
         * @var UploadedFile|Null file attribute
         */
        public $file;

        /**
         * @return array the validation rules.
         */
        public function rules()
        {
            return [
                [['file'], 'file'],
            ];
        }
    }`
In this part i set some paths hard to make sure thats not the error, it already goes wrong at setting the $image_name
`    public function actionUpload() {
        //$base_path = Yii::getAlias('@app');
        //$web_path = Yii::getAlias('@web');
        $model = new UploadForm();

        //if (Yii::$app->request->isPost) {
            
            
            $model->file = UploadedFile::getInstance($model, 'file');
            $image_name = $model->file->baseName . '.' . $model->file->extension;
            $image_path = '../../public_html/uploads/categorias/'.$image_name;
            $model->imagenes->saveAs($image_path);
            $res = '/uploads/categorias/'.$image_name;
            
        //}

        // Get file link
        $res = [
            'link' => '/uploads/categorias/'.$image_name,
        ];

        // Response data
        Yii::$app->response->format = Yii::$app->response->format = Response::FORMAT_JSON;
        return $res;
    }`

I hope someone can help me with what the issue is.

**Comment by dungphanxuan** [comment]
Hi @MarcoDuizer , froala upload so simple, so you need check Yii Upload file ok, then response full Url of Image.

![image](https://user-images.githubusercontent.com/10725732/33534111-19715d32-d8d8-11e7-8976-b4a113593e36.png)

**Comment by MarcoDuizer** [comment]
thanks for reply!!
But the error already start at the $image_name line in the code. There it gives the error, wich means the file isn't uploaded.

**Comment by imtiazmahbub** [comment]
Add these lines in your widget clientOptions:
```
            'imageUploadParams' => [
                Yii::$app->request->csrfParam => Yii::$app->request->getCsrfToken(),
            ],
            'imageManagerDeleteParams' => [
                Yii::$app->request->csrfParam => Yii::$app->request->getCsrfToken(),
            ],
```

So your code in view file will look like this:
```
    <?php
        $request = Yii::$app->request;
        echo froala\froalaeditor\FroalaEditorWidget::widget([
            'model' => $model,
            'attribute' => 'description',
            'options' => [
                // html attributes
                'id'=>'content'
            ],
            'clientOptions' => [
                'toolbarInline'=> false,
                'height' => 200,
                'theme' => 'royal',//optional: dark, red, gray, royal
                'language' => 'en_gb', // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
                'imageUploadParam' => 'file',
                'imageUploadParams' => [
                    $request->csrfParam => $request->getCsrfToken(),
                ],
                'imageManagerDeleteParams' => [
                    $request->csrfParam => $request->getCsrfToken(),
                ],
                'imageUploadURL' => \yii\helpers\Url::to(['articles/upload/'])
            ],
        ]);
    ?>
```
