### ISSUE TITLE
Using Amazon S3 with yii 2

### ISSUE THREAD

**Issue by kevinkt** [froala/yii2-froala-editor#25]
I'm not sure how to write the code to make Amazon S3 image upload work with Yii 2. Can someone help?

Here's what I have and the error is

Class 'FroalaEditor_S3' not found

`$config = array(
  // Your server timezone.
  'timezone' => 'Europe/Bucharest',
 
  // The name of your bucket.
  'bucket' => 'assets',
 
  // S3 region. If you are using the default us-east-1, it this can be ignored.
  // Read more on: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.
  'region' => 's3-us-west-1',
 
  // The folder where to upload the files.
  'keyStart' => 'assets',
 
  // File access.
  'acl' => 'public-read',
 
  // AWS keys.
  'accessKey' => 'ACCESSKEY',
  'secretKey' => 'MYSECRETKEY'
);
 
// Compute the signature.
$s3Hash = FroalaEditor_S3::getHash($config);
 
 
 

echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'contest_text',
    'options' => [
        // html attributes
        'id'=>'contest_text'
    ],
	'imageUploadToS3' => $s3Hash,
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'gray', //optional: dark, red, gray, royal
        'language' => 'en_gb', // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
			'toolbarButtons' => ['align', 'bold', 'italic', 'underline', 'formatOL', 'formatUL', 'paragraphFormat', 'fontFamily', 'fontSize', 'color', '|',  'insertImage', 'insertLink', 'html']
    ]`

**Comment by dungphanxuan** [comment]
I recommend you practice upload file local. Upload to s3 is sample like upload local, You need write action then editor config upload url to router

Code Example: Guider Upload https://github.com/froala/yii2-froala-editor#upload-example

**Comment by stefanneculai** [comment]
@kevinkt please find an example of using the FroalaEditor PHP SDK for uploading files here: https://github.com/froala/editor-php-sdk-example/blob/master/index.php#L325.
