### ISSUE TITLE
How can i use events from documentaion?

### ISSUE THREAD

**Issue by radeer** [froala/yii2-froala-editor#27]
Here is my floara widget:

`<?= \froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'content',
        'options' => [
            // html attributes
            'id'=>'content'
        ],
    'clientOptions' => [
        'toolbarInline'=> false,
        'height' => 200,
        'contentchnge' => 'alert(\'Hello\');',
        //'width' => 570,
        'theme' => 'royal',//optional: dark, red, gray, royal
        'language' => 'en_gb' ,
		'placeholderText' => 'Контент сообщения',
		
		'toolbarButtons' => ['html', 'bold', 'italic', '|','insertImage'],
        'imageUploadParam' => 'file',
        'imageUploadURL' => \yii\helpers\Url::to(['template/upload/'])
    ],
    'clientPlugins'=> ['code_view', 'image']
]); ?>`

How can i use the events from documentaion?
I want to use this:

froalaEditor.contentChanged (e, editor)
Triggered when the content from the Froala Rich Text Editor has changed.

e

The callback event.

editor

The editor instance.

CODE EXAMPLES
Set the contentChanged event:

$('.selector').on('froalaEditor.contentChanged', function (e, editor) {
  // Do something here.
});

**Comment by nikpok** [comment]
For issue -[froala/yii2-froala-editor#27](https://github.com/froala/yii2-froala-editor/issues/27)
for using the event contentchanged:-
go to the following path in your YII application -C:\Users\application_name\vendor\froala\wysiwyg-editor\html\events
(the froala folder in your application has been created by composer commands as mentioned in installation procedure)
now in the events folder select ContentChanged HTML file in editor.
in line no-61

<script> $(function(){ $('#edit').froalaEditor({ enter: $.FroalaEditor.ENTER_P }) .on ('froalaEditor.contentChanged', function () { alert("hii now content of froala editor is changed"); //console.log ('content changed'); }) }); </script>

Now,open the same file in browser and the alert box prompts whenever the content of the froala text editor is changed.
-in place of alert you can define your own functionality.

**Comment by iamnareshsaini** [comment]
You can use it in this way :- 
```
echo \froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => $attribute,
    'id' => !empty($unique_id) ? $unique_id : 'description-body',
    'clientOptions' => [
        'events' => [
            'contentChanged' => new \yii\web\JsExpression('function () {console.log("contentChanged");}')
        ],
............
```
