### ISSUE TITLE
Update with composer to latest version

### ISSUE THREAD

**Issue by bojanst** [froala/yii2-froala-editor#29]
`composer update` is not updating Widget to the latest version 
`composer install` does not update it too

i tried with multiple options 
"froala/yii2-froala-editor": "dev-master",
"froala/yii2-froala-editor": "@dev",
"froala/yii2-froala-editor": "^2.8.1",

nothing does the magic , 
Thanks!

**Comment by waitxd** [comment]
@stefanneculai Please make sure you pushed 2.9.1 to a packagist.org
