### ISSUE TITLE
add constants for widget backend (php) file

### ISSUE THREAD

**Issue by igorveremsky** [froala/yii2-froala-editor#30]
as described at docs https://www.froala.com/wysiwyg-editor/examples/enter froala client script file has constants for ENTER pressed action, 

> Possible values are $.FroalaEditor.ENTER_P, $.FroalaEditor.ENTER_DIV or $.FroalaEditor.ENTER_BR

but php version that construct widget don`t have it so you need manual find its value in js source file, and than do something like
```php
FroalaEditorWidget::className(), [
	'clientOptions' => [
		'enter' => 2 // $.FroalaEditor.ENTER_BR
	]
]
```
I think will be great to add this constants to [FroalaEditorWidget.php](https://github.com/froala/yii2-froala-editor/blob/master/src/FroalaEditorWidget.php) file and use it like:
```php
FroalaEditorWidget::className(), [
	'clientOptions' => [
		'enter' => FroalaEditorWidget::ENTER_BR
	]
]
```

**Comment by stefanneculai** [comment]
Nice touch!
