### ISSUE TITLE
Class 'froala\froalaeditor\FroalaEditorWidget' not found even it's installed in composer

### ISSUE THREAD

**Issue by edenramoneda** [froala/yii2-froala-editor#39]
I successfully installed froala editor in composer and it is on the list of composer.json but it keeps returned Class 'froala\froalaeditor\FroalaEditorWidget' not found

Here is my code
```
  <div class="form-group">
        <label class="control-label col-sm-2">Message:</label>
            <div class="col-sm-10">
                                       
                <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
                       'name' => 'content',
                       'options'=>[// html attributes
                       'id'=>'content'
                 ],
                       'clientOptions'=>[
                        'toolbarInline'=> false,
                        'theme' =>'royal',//optional: dark, red, gray, royal
                        'language'=>'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
                        ]
                   ]);; ?>
  </div>
```

**Comment by dungphanxuan** [comment]
Can you check more on your Vendor folder that package install success
![image](https://user-images.githubusercontent.com/10725732/68635317-c16af900-052a-11ea-9be1-4d3c284901ea.png)

**Comment by edenramoneda** [comment]
> Can you check more on your Vendor folder that package install success
> ![image](https://user-images.githubusercontent.com/10725732/68635317-c16af900-052a-11ea-9be1-4d3c284901ea
