### ISSUE TITLE
Can't get clientPlugins to work

### ISSUE THREAD

**Issue by cshehadi** [froala/yii2-froala-editor#8]
I'm not sure why, but when I use "clientPlugins," the only plugin I can get to work is "Fullscreen".  I've tried loading a number of other plugins and their buttons don't end up on the toolbar - except Fullscreen, which seems to work.  

For example, using 2.3.3, on Chrome 51 and this code, I see the fullscreen button, but no paragraph menu.

```
<?= \froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'Submission',
    'clientOptions' => [
        'toolbarButtons' => ['fullscreen', 'bold', 'italic', 'underline', '|', 'paragraphFormat'],
    ],
    'clientPlugins'=> ['fullscreen', 'paragraph_format'],
]); ?>
```

I see that it's loading the correct js files:

```
<script src="/assets/da3459a8/js/froala_editor.min.js"></script>
<script src="/assets/da3459a8/js/plugins/fullscreen.min.js"></script>
<script src="/assets/da3459a8/js/plugins/paragraph_format.min.js"></script>
<script src="/assets/da3459a8/js/languages/en_gb.js"></script>
```

and the js it generates looks ok to me:

```
$('#submissiondefault-submission').froalaEditor({
    "height":"80px",
    "theme":"dark",
    "language":"en_gb",
    "toolbarButtons":["fullscreen","bold","italic","underline","|","paragraphFormat"],
    "pluginsEnabled":["fullscreen","paragraph_format"]
});
```

If I comment out the 'clientPlugin' line:

```
<?= \froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'Submission',
    'clientOptions' => [
        'toolbarButtons' => ['fullscreen', 'bold', 'italic', 'underline', '|', 'paragraphFormat'],
    ],
 //   'clientPlugins'=> ['fullscreen', 'paragraph_format'],
]); ?>
```
Then it works - I can see the paragraph format menu in the toolbar.

But then it's loading all the js scripts for all possible plugins, which is what I'm trying to avoid.  

Does paragraph_format depend on some other file that's not getting loaded when I use clientPlugins?  Can you replicate this?

Thank you,

-Charlie

**Comment by dungphanxuan** [comment]
@stefanneculai please check assets file is ok.
Css File
![capture2](https://cloud.githubusercontent.com/assets/10725732/16335385/725d658c-3a30-11e6-9cdc-10dde214e893.PNG)
JS file
![capture3](https://cloud.githubusercontent.com/assets/10725732/16335395/7d83f462-3a30-11e6-82d0-26ecdb463b5a.PNG)

I think some file is missing.

**Comment by stefanneculai** [comment]
`pluginsEnabled` option should get the plugin names in camel-case, not with underscore. It should be `paragraphFormat`, not `paragraph_format`. It appears our docs are a bit confusing about this, so we'll update them shortly. @cshehadi please let me know if that works.

**Comment by cshehadi** [comment]
Hi - I think the yii2 widget may not be converting the arguments sent to clientPlugins to the appropriate naming convention for the js file (underscores) and plugin (camel case).

I've made the change you suggested:

```
'clientPlugins'=> ['fullscreen', 'paragraphFormat'],
```

but now it's not loading the correct js file (404:

```
<script src="/assets/d26b5f8e/js/plugins/paragraphFormat.min.js"></script>
```
though, the pluginsEnabled call now looks correct:

```
"pluginsEnabled":["fullscreen","paragraphFormat"]
```

**Comment by dungphanxuan** [comment]
@cshehadi please run composer update then check again. 
Demo
```php
<?= \froala\froalaeditor\FroalaEditorWidget::widget([
        'name' => 'body',
        'clientOptions' => [
            'toolbarInline'=> false,
            'height' => 200,
            'theme' =>'royal',//optional: dark, red, gray, royal
            'language'=>'en_gb' ,
            'toolbarButtons' => ['fullscreen', 'bold', 'italic', 'underline', '|', 'paragraphFormat'],
        ],
         'clientPlugins'=> ['fullscreen', 'paragraph_format'],
    ]); ?>
```

**Comment by cshehadi** [comment]
working beautifully, thanks.
