### ISSUE TITLE
Problem with Requirements

### ISSUE THREAD

**Issue by not--p** [froala/yii2-froala-editor#9]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - froala/yii2-froala-editor 2.3.3 requires bower-asset/froala-wysiwyg-editor 2.3.3 -> no matching package found.
    - froala/yii2-froala-editor 2.3.2 requires bower-asset/froala-wysiwyg-editor 2.3.2 -> no matching package found.
    - froala/yii2-froala-editor 2.3.1 requires bower-asset/froala-wysiwyg-editor 2.3.1 -> no matching package found.
    - froala/yii2-froala-editor 2.3.0 requires bower-asset/froala-wysiwyg-editor 2.3.0 -> no matching package found.
    - froala/yii2-froala-editor 2.2.4 requires bower-asset/froala-wysiwyg-editor 2.2.4 -> no matching package found.
    - froala/yii2-froala-editor 2.2.3 requires bower-asset/froala-wysiwyg-editor 2.2.3 -> no matching package found.
    - froala/yii2-froala-editor 2.2.2 requires bower-asset/froala-wysiwyg-editor 2.2.2 -> no matching package found.
    - froala/yii2-froala-editor 2.2.1 requires bower-asset/froala-wysiwyg-editor 2.2.1 -> no matching package found.
    - froala/yii2-froala-editor 2.2.0 requires bower-asset/froala-wysiwyg-editor 2.2.0 -> no matching package found.
    - froala/yii2-froala-editor 2.1.0 requires bower-asset/froala-wysiwyg-editor 2.1.0 -> no matching package found.
    - froala/yii2-froala-editor 2.0.5 requires bower-asset/froala-wysiwyg-editor 2.0.5 -> no matching package found.
    - froala/yii2-froala-editor 2.0.3 requires bower-asset/froala-wysiwyg-editor 2.0.3 -> no matching package found.
    - froala/yii2-froala-editor 2.0.2 requires bower-asset/froala-wysiwyg-editor 2.0.2 -> no matching package found.
    - froala/yii2-froala-editor 2.0.1 requires bower-asset/froala-wysiwyg-editor ^2.0 -> no matching package found.
    - Installation request for froala/yii2-froala-editor * -> satisfiable by froala/yii2-froala-editor[2.0.1, 2.0.2, 2.0.3, 2.0.5, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by dungphanxuan** [comment]
@not--p please run command
php composer.phar global require "fxp/composer-asset-plugin:1.0.0"

**Comment by not--p** [comment]
@dungphanxuan Thanks for your reply. Here's the output:

`Changed current directory to /home/jason/.composer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fxp/composer-asset-plugin 1.0.0 -> satisfiable by fxp/composer-asset-plugin[v1.0.0].
    - fxp/composer-asset-plugin v1.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.`

**Comment by dungphanxuan** [comment]
@not--p i think composer has problem, please reinstall composer and folow install yii2
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer
Then install plugin

**Comment by not--p** [comment]
I wont have time to work on this. Thank you.

**Comment by OneHey** [comment]
Thanks for your help
